export const CONSTANTS = {
    WELCOME: 'Welcome ',
    LOGIN_HEADING: 'Welcome to Logistics Orchestration',
    LOGOUT_MESSAGE: 'You have successfully logged out!',
    USERNAME: 'Username',
    USERNAME_EMPTY_MESSGAE: 'Username is required',
    FORGOT_USERNAME: 'Forgot Username',
    LOGIN: 'Login',
    LOGIN_WITH_SSO: 'Login with SSO',
    PREVIOUS: 'Previous Vehicle',
    PREVIOUS_VEHICLE: 'Previous Vehicle',
    CURRENT_VEHICLE: 'Current Vehicle',
    PENDING_SCAN: "PENDING SCAN",
    EXPECTED_COMPLETION: 'Expected Completion',
    EXPECTED_INSTALL_TIME: 'Expected Install Time',
    DROP_OFF_LOCATION: 'Drop Off Location',
    PICK_UP_LOCATION: 'Pick Up Location',
    NEXT_VEHICLE: 'Next Vehicle',
    PLANNED_START_TIME: 'Planned Start Time',
    NEXT_VEHICLE_IS_NOT_AVAILABLE: 'Please contact your supervisor to get information about next VIN',
    LINE: 'Line',
    SHOP: 'Shop',
    CODE: 'Code',
    ACCESSORY_DESCRIPTION: 'Accessory Description',
    ACCESSORY_PART_NUMBER: 'Accessory Part Number(s)',
    EXP_TIME: 'Exp. Time',
    INSTALLED: 'Installed',
    NOT_INSTALLED: 'Not Installed',
    SUBMIT: "Submit",
    CURRENT_VEHICLE_INSTALLATION: 'Current Vehicle Installation',
    SCAN_NEXT_VIN: 'Scan Next VIN',
    VIN_ID_EMPTY_MESSAGE: 'VIN is required',
    VIN_ID_INVALID_MESSAGE: 'VIN not found',
    ENTER_VIN: 'Enter VIN',
    NOT_INSTALLED_REASON: 'Not Installed Reason',
    CANCEL: "Cancel",
    CONFIRM: "CONFIRM",
    YES: "Yes",
    NO: "No",
    REMOVE: "Remove",
    CONTINUE: "Continue",
    VEHICLES: 'Vehicles',
    HOURS: 'Hours',
    TEAM_MEMBER_AT_STALL: 'Team Member(s) at Stall',
    STALL_PROGRESS_CURRENT_SHIFT: 'Stall Progress - Current Shift ',
    SHOP_PROGRESS_CURRENT_SHIFT: 'Production Line Progress - Current Shift',
    PLANNED: 'Planned',
    VEHICLE_SUCCESS_MESSAGE: 'Vehicle accessory installation was successfully completed',
    VIN_ID_INVALID_MESSAGE1: 'Warning - Inventory Code DO - UNIT DOWN FOR VIN',
    VIN_ID_INVALID_MESSAGE2: "This vehicle's inventory code is D0 - Unit Down for VIN",
    VIN_ID_INVALID_MESSAGE3: 'Choose to continue installation or scan another VIN',
    YES_CANCEL_CURRENT_VIN: "Yes cancel current VIN",
    NO_BACK_TO_CUURENT_VIN: "No back to current VIN",
    CANCEL_MODAL_HEADER: "Are you sure you want to cancel and return to main page?",
    ACKNOWLEDGED_MODAL_HEADER: "Are you sure you want to continue?",
    REMOVE_TEAM_MEMBER_MODAL_HEADER: "Are you sure you want to remove",
    REMOVE_TEAM_MEMBER_MODAL_CONTENT: "Click 'Cancel' or 'X' to go back without making any changes. Click 'Remove' to remove the team member.",
    CONFIRM_MODAL_CONTENT: "Click 'No' to stay on current vehicle. Click 'Yes' to go back to the main page and process next vehicle. If you click 'Yes', your current vehicle progress will not be saved.",
    TABLE_SUBMIT_MODAL_HEADER: "Are you sure you want to submit the vehicle accessory installations?",
    TABLE_SUBMIT_MODAL_CONTENT: "Please review the 'Not Installed' and 'Installed' accessories below. Click 'No' or 'X' to go back and modify. Click 'Yes' to submit.",
    MANAGER_SITE_METRIC_SHOP_FLOOR_HEADER: "Progress by Production Line",
    MANAGER_SITE_METRIC_SHOP_FLOOR_SUB_HEADER: "Hover on a line for additional metrics.",
    IS_PAST: 'Selected Effective Date Time is in the past',
    EFFECTIVE_DATE: 'Effective Date',
    EFFECTIVE_TIME: 'Effective Time', 
    SITE_CONFIGURATION: 'Site Configuration',
    REVIEW_CHANGES: 'Review Changes',
    SETTING_ICON: 'settings icon',
    LOADING: "Loading",
    SITEHOME: "Site Home",
    LONGBEACH: "LONG BEACH",
    PRINCETON: "PRINCETON",
    SEARCH_WORKDAY_ID: "Search WorkdayID ...",
    SELECT_TEAM_MEMBER: "Select Team Member...",
    COMPLETE_ON_TIME: "COMPLETE - ON TIME",
    COMPLETE_LATE: "COMPLETE - LATE",
    TIME_ELASPED: "TIME ELASPED:",
    COMPLETE: "COMPLETE",
    INCOMPLETE: "INCOMPLETE",
    ACTUAL_COMPLETION: "Actual Completion",
    ACTUAL_INSTALL_TIME: "Actual Install Time",
    LINESTAG: "LINE",
    STAGING: "STAGING",
    VIN_IMG_NOT_AVAILABLE: "VIN image not available",
    VIN_IMG_ALT: "Toyota Car Image",
    NETWORK_ERROR: "Something went wrong while submitting, please try again",
    DESCRIPTION: "Description",
    REASON: "Reason",
    STATUS: "Status",
    SELECT_REASON: "Select reason",
    TOOLTIP_HOVER_CONTENT1: "Click the links below to access",
    TOOLTIP_HOVER_CONTENT2: "each accessory",
    TOOLTIP_HOVER_CONTENT3: "Standard Work Sheet.",
    VIN_DOWN_MESSAGE1: "Please contact your team lead or supervisor before proceeding",
    VIN_DOWN_MESSAGE2: "to continue processing the current vehicle",
    VIN_DOWN_MESSAGE3: "to go back to the main page and process the next vehicle",
    NOT_INSTALLED_REASON_DESC:"Not Installed Reason Descriptions",
    METRICS: "Metrics",    
    COMPLETION_PERFORMANCE: "Installation Performance of Scheduled Vehicles",
    COMPLETE_METRIC_ON_TIME: "On Time",
    COMPLETE_METRIC_LATE: "Late",
    INSTALLATION_EXCEPTIONS: "Installation Exceptions",
    VEHICLES_AFFECTED: "Vehicles Affected",
    PROGRESS_AGAINST_PLAN: "Progress Against Plan",
    PROGRESS: "Progress",
    TOTAL_PLANNED: "Total Planned",
    TOTAL_COMPLETE: "Total Complete",
    REFRESH_ERROR: "Failed to refresh data. Please try again later.",
    PST_TIME_ZONE: "America/Los_Angeles"
};

